-- 向TiDB数据库的表中增加0200业务的配置
-- 分区表配置

delete from PARTITION_CONFIG where table_name in ('BL_0200_ACC_ORI_JKPAY','BL_0200_ACC_ORI_UPAY','BL_0200_ACC_COM_PAYAGENT_UPAY','BL_0200_ACC_DIF_MERCHANT');
-- 说明：第二个字段的值是数据库的名称，需要按照实际情况将值替换。
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
