-- 0100建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0100_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0100_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0100_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0100_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0100_ACC_ORI_UPAY;
 CREATE TABLE `BL_0100_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0100_ACC_ORI_UPAY ADD INDEX INDEX_BL_0100_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0100_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0100_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0100_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0100_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0100_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0100_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0100_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0100_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0200建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0200_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0200_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0200_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0200_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0200_ACC_ORI_UPAY;
 CREATE TABLE `BL_0200_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0200_ACC_ORI_UPAY ADD INDEX INDEX_BL_0200_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0200_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0200_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0200_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0200_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0200_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0200_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0200_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0200_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0210建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0210_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0210_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0210_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0210_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0210_ACC_ORI_UPAY;
 CREATE TABLE `BL_0210_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0210_ACC_ORI_UPAY ADD INDEX INDEX_BL_0210_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0210_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0210_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0210_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0210_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0210_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0210_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0210_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0210_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0240建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0240_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0240_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0240_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0240_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0240_ACC_ORI_UPAY;
 CREATE TABLE `BL_0240_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0240_ACC_ORI_UPAY ADD INDEX INDEX_BL_0240_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0240_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0240_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0240_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0240_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0240_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0240_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0240_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0240_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0290建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0290_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0290_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0290_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0290_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0290_ACC_ORI_UPAY;
 CREATE TABLE `BL_0290_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0290_ACC_ORI_UPAY ADD INDEX INDEX_BL_0290_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0290_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0290_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0290_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0290_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0290_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0290_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0290_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0290_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0311建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0311_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0311_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0311_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0311_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0311_ACC_ORI_UPAY;
 CREATE TABLE `BL_0311_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0311_ACC_ORI_UPAY ADD INDEX INDEX_BL_0311_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0311_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0311_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0311_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0311_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0311_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0311_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0311_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0311_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0351建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0351_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0351_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0351_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0351_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0351_ACC_ORI_UPAY;
 CREATE TABLE `BL_0351_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0351_ACC_ORI_UPAY ADD INDEX INDEX_BL_0351_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0351_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0351_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0351_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0351_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0351_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0351_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0351_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0351_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0371建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0371_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0371_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0371_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0371_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0371_ACC_ORI_UPAY;
 CREATE TABLE `BL_0371_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0371_ACC_ORI_UPAY ADD INDEX INDEX_BL_0371_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0371_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0371_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0371_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0371_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0371_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0371_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0371_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0371_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0431建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0431_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0431_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0431_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0431_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0431_ACC_ORI_UPAY;
 CREATE TABLE `BL_0431_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0431_ACC_ORI_UPAY ADD INDEX INDEX_BL_0431_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0431_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0431_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0431_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0431_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0431_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0431_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0431_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0431_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0471建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0471_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0471_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0471_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0471_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0471_ACC_ORI_UPAY;
 CREATE TABLE `BL_0471_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0471_ACC_ORI_UPAY ADD INDEX INDEX_BL_0471_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0471_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0471_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0471_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0471_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0471_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0471_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0471_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0471_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0551建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0551_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0551_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0551_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0551_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0551_ACC_ORI_UPAY;
 CREATE TABLE `BL_0551_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0551_ACC_ORI_UPAY ADD INDEX INDEX_BL_0551_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0551_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0551_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0551_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0551_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0551_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0551_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0551_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0551_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0571建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0571_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0571_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0571_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0571_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0571_ACC_ORI_UPAY;
 CREATE TABLE `BL_0571_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0571_ACC_ORI_UPAY ADD INDEX INDEX_BL_0571_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0571_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0571_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0571_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0571_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0571_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0571_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0571_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0571_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0731建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0731_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0731_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0731_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0731_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0731_ACC_ORI_UPAY;
 CREATE TABLE `BL_0731_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0731_ACC_ORI_UPAY ADD INDEX INDEX_BL_0731_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0731_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0731_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0731_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0731_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0731_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0731_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0731_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0731_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0771建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0771_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0771_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0771_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0771_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0771_ACC_ORI_UPAY;
 CREATE TABLE `BL_0771_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0771_ACC_ORI_UPAY ADD INDEX INDEX_BL_0771_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0771_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0771_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0771_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0771_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0771_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0771_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0771_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0771_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0791建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0791_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0791_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0791_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0791_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0791_ACC_ORI_UPAY;
 CREATE TABLE `BL_0791_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0791_ACC_ORI_UPAY ADD INDEX INDEX_BL_0791_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0791_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0791_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0791_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0791_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0791_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0791_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0791_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0791_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0891建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0891_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0891_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0891_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0891_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0891_ACC_ORI_UPAY;
 CREATE TABLE `BL_0891_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0891_ACC_ORI_UPAY ADD INDEX INDEX_BL_0891_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0891_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0891_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0891_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0891_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0891_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0891_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0891_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0891_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0898建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0898_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0898_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0898_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0898_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0898_ACC_ORI_UPAY;
 CREATE TABLE `BL_0898_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0898_ACC_ORI_UPAY ADD INDEX INDEX_BL_0898_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0898_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0898_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0898_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0898_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0898_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0898_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0898_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0898_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0931建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0931_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0931_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0931_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0931_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0931_ACC_ORI_UPAY;
 CREATE TABLE `BL_0931_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0931_ACC_ORI_UPAY ADD INDEX INDEX_BL_0931_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0931_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0931_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0931_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0931_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0931_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0931_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0931_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0931_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0951建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0951_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0951_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0951_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0951_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0951_ACC_ORI_UPAY;
 CREATE TABLE `BL_0951_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0951_ACC_ORI_UPAY ADD INDEX INDEX_BL_0951_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0951_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0951_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0951_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0951_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0951_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0951_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0951_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0951_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0971建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0971_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0971_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0971_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0971_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0971_ACC_ORI_UPAY;
 CREATE TABLE `BL_0971_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0971_ACC_ORI_UPAY ADD INDEX INDEX_BL_0971_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0971_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0971_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0971_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0971_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0971_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0971_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0971_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0971_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


-- 0991建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS BL_0991_ACC_ORI_JKPAY;
 CREATE TABLE `BL_0991_ACC_ORI_JKPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金科原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0991_ACC_ORI_JKPAY ADD INDEX INDEX_BL_0991_ACC_ORI_JKPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0991_ACC_ORI_UPAY;
 CREATE TABLE `BL_0991_ACC_ORI_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一支付原始对账数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0991_ACC_ORI_UPAY ADD INDEX INDEX_BL_0991_ACC_ORI_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0991_ACC_COM_PAYAGENT_UPAY;
 CREATE TABLE `BL_0991_ACC_COM_PAYAGENT_UPAY` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0991_ACC_COM_PAYAGENT_UPAY ADD INDEX INDEX_BL_0991_ACC_COM_PAYAGENT_UPAY_SETTLE_DATE(SETTLE_DATE);

DROP TABLE IF EXISTS BL_0991_ACC_DIF_MERCHANT;
 CREATE TABLE `BL_0991_ACC_DIF_MERCHANT` (
  `ID` varchar(50) NOT NULL COMMENT 'ID',
  `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
  `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
  `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
  `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户差异数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190928 VALUES LESS THAN ('20190929') ENGINE = InnoDB,
 PARTITION p20190929 VALUES LESS THAN ('20190930') ENGINE = InnoDB,
 PARTITION p20190930 VALUES LESS THAN ('20191001') ENGINE = InnoDB);
alter table BL_0991_ACC_DIF_MERCHANT ADD INDEX INDEX_BL_0991_ACC_DIF_MERCHANT_SETTLE_DATE(SETTLE_DATE);


