-- 向TiDB数据库的表中新增配置
-- 分区表配置
-- 0100
delete from PARTITION_CONFIG where table_name in ('BL_0100_ACC_ORI_JKPAY','BL_0100_ACC_ORI_UPAY','BL_0100_ACC_COM_PAYAGENT_UPAY','BL_0100_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0100_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0100_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0100_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0100_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0200
delete from PARTITION_CONFIG where table_name in ('BL_0200_ACC_ORI_JKPAY','BL_0200_ACC_ORI_UPAY','BL_0200_ACC_COM_PAYAGENT_UPAY','BL_0200_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0200_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0210
delete from PARTITION_CONFIG where table_name in ('BL_0210_ACC_ORI_JKPAY','BL_0210_ACC_ORI_UPAY','BL_0210_ACC_COM_PAYAGENT_UPAY','BL_0210_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0210_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0210_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0210_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0210_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0220
delete from PARTITION_CONFIG where table_name in ('BL_0220_ACC_ORI_JKPAY','BL_0220_ACC_ORI_UPAY','BL_0220_ACC_COM_PAYAGENT_UPAY','BL_0220_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0220_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0220_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0220_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0220_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0230
delete from PARTITION_CONFIG where table_name in ('BL_0230_ACC_ORI_JKPAY','BL_0230_ACC_ORI_UPAY','BL_0230_ACC_COM_PAYAGENT_UPAY','BL_0230_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0230_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0230_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0230_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0230_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0240
delete from PARTITION_CONFIG where table_name in ('BL_0240_ACC_ORI_JKPAY','BL_0240_ACC_ORI_UPAY','BL_0240_ACC_COM_PAYAGENT_UPAY','BL_0240_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0240_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0240_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0240_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0240_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0270
delete from PARTITION_CONFIG where table_name in ('BL_0270_ACC_ORI_JKPAY','BL_0270_ACC_ORI_UPAY','BL_0270_ACC_COM_PAYAGENT_UPAY','BL_0270_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0270_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0270_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0270_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0270_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0280
delete from PARTITION_CONFIG where table_name in ('BL_0280_ACC_ORI_JKPAY','BL_0280_ACC_ORI_UPAY','BL_0280_ACC_COM_PAYAGENT_UPAY','BL_0280_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0280_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0280_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0280_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0280_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0290
delete from PARTITION_CONFIG where table_name in ('BL_0290_ACC_ORI_JKPAY','BL_0290_ACC_ORI_UPAY','BL_0290_ACC_COM_PAYAGENT_UPAY','BL_0290_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0290_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0290_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0290_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0290_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0311
delete from PARTITION_CONFIG where table_name in ('BL_0311_ACC_ORI_JKPAY','BL_0311_ACC_ORI_UPAY','BL_0311_ACC_COM_PAYAGENT_UPAY','BL_0311_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0311_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0311_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0311_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0311_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0351
delete from PARTITION_CONFIG where table_name in ('BL_0351_ACC_ORI_JKPAY','BL_0351_ACC_ORI_UPAY','BL_0351_ACC_COM_PAYAGENT_UPAY','BL_0351_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0351_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0351_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0351_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0351_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0371
delete from PARTITION_CONFIG where table_name in ('BL_0371_ACC_ORI_JKPAY','BL_0371_ACC_ORI_UPAY','BL_0371_ACC_COM_PAYAGENT_UPAY','BL_0371_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0371_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0371_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0371_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0371_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0431
delete from PARTITION_CONFIG where table_name in ('BL_0431_ACC_ORI_JKPAY','BL_0431_ACC_ORI_UPAY','BL_0431_ACC_COM_PAYAGENT_UPAY','BL_0431_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0431_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0431_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0431_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0431_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0451
delete from PARTITION_CONFIG where table_name in ('BL_0451_ACC_ORI_JKPAY','BL_0451_ACC_ORI_UPAY','BL_0451_ACC_COM_PAYAGENT_UPAY','BL_0451_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0451_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0451_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0451_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0451_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0471
delete from PARTITION_CONFIG where table_name in ('BL_0471_ACC_ORI_JKPAY','BL_0471_ACC_ORI_UPAY','BL_0471_ACC_COM_PAYAGENT_UPAY','BL_0471_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0471_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0471_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0471_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0471_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0551
delete from PARTITION_CONFIG where table_name in ('BL_0551_ACC_ORI_JKPAY','BL_0551_ACC_ORI_UPAY','BL_0551_ACC_COM_PAYAGENT_UPAY','BL_0551_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0551_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0551_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0551_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0551_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0571
delete from PARTITION_CONFIG where table_name in ('BL_0571_ACC_ORI_JKPAY','BL_0571_ACC_ORI_UPAY','BL_0571_ACC_COM_PAYAGENT_UPAY','BL_0571_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0571_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0571_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0571_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0571_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0591
delete from PARTITION_CONFIG where table_name in ('BL_0591_ACC_ORI_JKPAY','BL_0591_ACC_ORI_UPAY','BL_0591_ACC_COM_PAYAGENT_UPAY','BL_0591_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0591_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0591_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0591_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0591_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0731
delete from PARTITION_CONFIG where table_name in ('BL_0731_ACC_ORI_JKPAY','BL_0731_ACC_ORI_UPAY','BL_0731_ACC_COM_PAYAGENT_UPAY','BL_0731_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0731_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0731_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0731_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0731_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0771
delete from PARTITION_CONFIG where table_name in ('BL_0771_ACC_ORI_JKPAY','BL_0771_ACC_ORI_UPAY','BL_0771_ACC_COM_PAYAGENT_UPAY','BL_0771_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0771_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0771_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0771_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0771_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0791
delete from PARTITION_CONFIG where table_name in ('BL_0791_ACC_ORI_JKPAY','BL_0791_ACC_ORI_UPAY','BL_0791_ACC_COM_PAYAGENT_UPAY','BL_0791_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0791_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0791_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0791_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0791_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0851
delete from PARTITION_CONFIG where table_name in ('BL_0851_ACC_ORI_JKPAY','BL_0851_ACC_ORI_UPAY','BL_0851_ACC_COM_PAYAGENT_UPAY','BL_0851_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0851_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0851_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0851_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0851_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0891
delete from PARTITION_CONFIG where table_name in ('BL_0891_ACC_ORI_JKPAY','BL_0891_ACC_ORI_UPAY','BL_0891_ACC_COM_PAYAGENT_UPAY','BL_0891_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0891_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0891_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0891_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0891_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0898
delete from PARTITION_CONFIG where table_name in ('BL_0898_ACC_ORI_JKPAY','BL_0898_ACC_ORI_UPAY','BL_0898_ACC_COM_PAYAGENT_UPAY','BL_0898_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0898_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0898_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0898_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0898_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0931
delete from PARTITION_CONFIG where table_name in ('BL_0931_ACC_ORI_JKPAY','BL_0931_ACC_ORI_UPAY','BL_0931_ACC_COM_PAYAGENT_UPAY','BL_0931_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0931_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0931_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0931_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0931_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0951
delete from PARTITION_CONFIG where table_name in ('BL_0951_ACC_ORI_JKPAY','BL_0951_ACC_ORI_UPAY','BL_0951_ACC_COM_PAYAGENT_UPAY','BL_0951_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0951_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0951_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0951_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0951_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0971
delete from PARTITION_CONFIG where table_name in ('BL_0971_ACC_ORI_JKPAY','BL_0971_ACC_ORI_UPAY','BL_0971_ACC_COM_PAYAGENT_UPAY','BL_0971_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0971_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0971_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0971_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0971_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
-- 0991
delete from PARTITION_CONFIG where table_name in ('BL_0991_ACC_ORI_JKPAY','BL_0991_ACC_ORI_UPAY','BL_0991_ACC_COM_PAYAGENT_UPAY','BL_0991_ACC_DIF_MERCHANT');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0991_ACC_ORI_JKPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0991_ACC_ORI_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0991_ACC_COM_PAYAGENT_UPAY', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
insert into PARTITION_CONFIG(TABLE_NAME,DATABASE_NAME,PARTITION_NUMBER,PARTITION_TYPE,IS_EFFECT,DATASOURCE_NAME) VALUES  ('BL_0991_ACC_DIF_MERCHANT', 'csv_db', 3, 'day', 1,'TiDB-Db-A');
