-- 0451建表SQL脚本
-- SET NAMES utf8mb4;
-- SET FOREIGN_KEY_CHECKS = 0;
-- 0451补全数据表
DROP TABLE IF EXISTS BL_0451_ACC_COM_PAYAGENT_MERCHANT;
 CREATE TABLE `BL_0451_ACC_COM_PAYAGENT_MERCHANT` (
 `ID` varchar(50) NOT NULL COMMENT 'ID',
 `BUSILINE` varchar(30) DEFAULT NULL COMMENT '业务线',
 `SETTLE_DATE` varchar(30) NOT NULL COMMENT '账期日',
 `PROVINCE` varchar(30) DEFAULT NULL COMMENT '省编码',
 `JSON` json DEFAULT NULL COMMENT 'JSON集'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='补全数据表'
PARTITION BY RANGE  COLUMNS(SETTLE_DATE)
(PARTITION p20190303 VALUES LESS THAN ('20190304') ENGINE = InnoDB,
 PARTITION p20190304 VALUES LESS THAN ('20190305') ENGINE = InnoDB,
 PARTITION p20190305 VALUES LESS THAN ('20190306') ENGINE = InnoDB);
 ALTER TABLE BL_0451_ACC_COM_PAYAGENT_MERCHANT ADD INDEX INDEX_BL_0451_ACC_COM_PAYAGENT_MERCHANT_SETTLE_DATE(SETTLE_DATE);


